language: python
dist: xenial
os: linux
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
jobs:
  include:
    - python: 3.8
      name: mypy
      env: TOXENV=mypy
    - python: 3.8
      name: docs
      env: TOXENV=docs
  allow_failures:
    - python: "3.9-dev"
install:
  - pip install -U pip tox-travis poetry
script:
  - tox

before_deploy:
  - pip install -U pip poetry
  - poetry config repositories.deploypi $PYPI_SERVER
  - poetry config http-basic.deploypi $PYPI_USER $PYPI_PASSWORD

deploy:
  provider: script
  script: poetry publish -r deploypi
  on:
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"
    branch: master
    tags: true
  skip_existing: true
