language: python
dist: xenial
os: linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
jobs:
  include:
    - python: 3.8
      name: mypy
      env: TOXENV=mypy
  allow_failures:
    - python: "3.9-dev"
install:
  - pip install -U tox-travis poetry
script:
  - tox
