language: python
dist: xenial
os: linux
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
jobs:
  include:
    - python: 3.8
      name: mypy
      env: TOXENV=mypy
    - python: 3.8
      name: docs
      env: TOXENV=docs
  allow_failures:
    - python: "3.9-dev"
install:
  - pip install -U tox-travis poetry
script:
  - tox

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  server: $PYPI_SERVER
  on:
    branch: master
    tags: true
  skip_existing: true
